---
title: "Lung_ST_scrabian"
author: "Yelin Zhao"
date: "2024-02-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load packages
```{r}
library(Seurat)
library(ggplot2)
library(gridExtra)
library(patchwork)
```

# setup locations
```{r}

```


# load data
```{r}
Patient1 = load('GSE189487 Lung cancer ST/seurat_ST1.rda')
plot1 <- VlnPlot(seurat, features = "nCount_Spatial", pt.size = 0.1) + NoLegend()
plot2 <- SpatialFeaturePlot(seurat, features = "nCount_Spatial") + theme(legend.position = "right")
wrap_plots(plot1, plot2)
```

```{r}
seurat <- SCTransform(seurat, assay = "Spatial", verbose = FALSE)
seurat <- RunPCA(seurat, assay = "SCT", verbose = FALSE)
seurat <- FindNeighbors(seurat, reduction = "pca", dims = 1:30)
seurat <- FindClusters(seurat, verbose = FALSE)
seurat <- RunUMAP(seurat, reduction = "pca", dims = 1:30)
p1 <- DimPlot(seurat, reduction = "umap", label = TRUE)
p2 <- SpatialDimPlot(seurat, label = TRUE, label.size = 3)
p1
p2
```

